#!/usr/bin/env python3
"""Analyze Clip Cropper boundary feedback JSONL.

Input: boundary-feedback.jsonl generated by the plugin.
Output: human-readable metrics grouped by preset and decision/error type.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean, median
from typing import Any, Iterable


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(f"warning: skipping invalid JSON at line {line_no}: {exc}")
    return rows


def finite_number(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return float(value)
    return None


def abs_values(rows: Iterable[dict[str, Any]], key: str) -> list[float]:
    result: list[float] = []
    for row in rows:
        value = finite_number(row.get(key))
        if value is not None:
            result.append(abs(value))
    return result


def pct_within(values: list[float], threshold: float) -> float:
    if not values:
        return 0.0
    return 100.0 * sum(1 for value in values if value <= threshold) / len(values)


def structured_feedback(row: dict[str, Any]) -> dict[str, Any]:
    feedback = row.get("explicit_structured_feedback")
    return feedback if isinstance(feedback, dict) else {}


def feedback_bool(row: dict[str, Any], key: str) -> bool:
    feedback = structured_feedback(row)
    return feedback.get(key, row.get(f"feedback_{key}")) is True


def diagnostic_rejection_reason(row: dict[str, Any]) -> str:
    feedback = structured_feedback(row)
    return str(feedback.get("diagnostic_rejection_reason") or row.get("diagnostic_rejection_reason") or "")


def is_boundary_recoverable_feedback(row: dict[str, Any]) -> bool:
    if str(row.get("generated_feedback_class", "")) == "bad_topic" or feedback_bool(row, "bad_topic"):
        return False
    if (
        str(row.get("generated_feedback_class", "")) == "good_topic_bad_boundary"
        or feedback_bool(row, "boundary_recoverable")
        or feedback_bool(row, "good_topic_bad_boundary")
        or feedback_bool(row, "incomplete_but_recoverable")
    ):
        return True
    return row.get("decision") in {"adjusted", "approved_adjusted"} and is_incomplete_viewer_arc(row)


def is_incomplete_viewer_arc(row: dict[str, Any]) -> bool:
    return "incomplete_viewer_arc" in diagnostic_rejection_reason(row)


def is_ignored_or_weak_training_signal(row: dict[str, Any]) -> bool:
    feedback_class = str(row.get("generated_feedback_class", ""))
    return (
        row.get("decision") == "ignored_diagnostic"
        or row.get("explicit_review_decision") == "ignored_diagnostic"
        or feedback_class in {"ignored_diagnostic", "weak_negative"}
        or feedback_bool(row, "ignore_for_training")
        or feedback_bool(row, "weak_negative")
    )


def is_calibratable_feedback(row: dict[str, Any]) -> bool:
    if row.get("decision") in {"removed_unrated", "ignored_diagnostic"}:
        return False
    if is_ignored_or_weak_training_signal(row):
        return False
    if row.get("event") == "review_rejected" and not row.get("explicit_review_decision"):
        return False
    return True


def print_group(name: str, rows: list[dict[str, Any]]) -> None:
    print(f"\n== {name} ==")
    print(f"records: {len(rows)}")
    calibratable_rows = [row for row in rows if is_calibratable_feedback(row)]
    ignored_cancel_rows = len([row for row in rows if row.get("event") == "review_rejected" and not row.get("explicit_review_decision")])
    print(f"calibratable_records: {len(calibratable_rows)}")
    if ignored_cancel_rows:
        print(f"ignored_ambiguous_cancel_rows: {ignored_cancel_rows}")
    decisions = Counter(str(row.get("decision", "unknown")) for row in rows)
    print("decisions:", ", ".join(f"{k}={v}" for k, v in decisions.most_common()))

    rows_for_stats = calibratable_rows or rows
    start_types = Counter(str(row.get("start_error_type", "unknown")) for row in rows_for_stats)
    end_types = Counter(str(row.get("end_error_type", "unknown")) for row in rows_for_stats)
    recoverable_boundary = sum(1 for row in rows_for_stats if is_boundary_recoverable_feedback(row))
    incomplete_arcs = sum(1 for row in rows_for_stats if is_incomplete_viewer_arc(row))
    bad_topic = sum(1 for row in rows_for_stats if str(row.get("generated_feedback_class", "")) == "bad_topic" or feedback_bool(row, "bad_topic"))
    ignored_or_weak = sum(1 for row in rows if is_ignored_or_weak_training_signal(row))
    print("start_error_type:", ", ".join(f"{k}={v}" for k, v in start_types.most_common()))
    print("end_error_type:", ", ".join(f"{k}={v}" for k, v in end_types.most_common()))
    print(f"feedback_classes: recoverable_boundary={recoverable_boundary} incomplete_viewer_arc={incomplete_arcs} bad_topic={bad_topic} ignored_or_weak_training={ignored_or_weak}")

    start_errors = abs_values(rows_for_stats, "start_error_sec")
    end_errors = abs_values(rows_for_stats, "end_error_sec")
    if start_errors:
        print(
            "start_abs_error_sec: "
            f"mean={mean(start_errors):.2f} median={median(start_errors):.2f} "
            f"<=3s={pct_within(start_errors, 3):.1f}% <=5s={pct_within(start_errors, 5):.1f}% "
            f"<=8s={pct_within(start_errors, 8):.1f}%"
        )
    if end_errors:
        print(
            "end_abs_error_sec: "
            f"mean={mean(end_errors):.2f} median={median(end_errors):.2f} "
            f"<=3s={pct_within(end_errors, 3):.1f}% <=5s={pct_within(end_errors, 5):.1f}% "
            f"<=8s={pct_within(end_errors, 8):.1f}%"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("feedback_jsonl", type=Path)
    args = parser.parse_args()

    rows = load_jsonl(args.feedback_jsonl)
    if not rows:
        print("No feedback records found.")
        return 1

    print_group("all", rows)

    by_preset: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_preset[str(row.get("preset", "unknown"))].append(row)
    for preset, preset_rows in sorted(by_preset.items(), key=lambda item: (-len(item[1]), item[0])):
        print_group(f"preset:{preset}", preset_rows)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
